### ISSUE TITLE
[BUG] The redis service fails with an error reading the configuration file

### ISSUE THREAD

**Issue by etuck** [Xoconoch/spotizerr#137]
**Describe the bug**
The redis service fails to start with the following error: 

```
Starting Redis Server
spotizerr-redis  | 
spotizerr-redis  | *** FATAL CONFIG FILE ERROR (Redis 8.0.2) ***
spotizerr-redis  | Reading the configuration file, at line 2
spotizerr-redis  | >>> 'requirepass "--appendonly" "yes"'
spotizerr-redis  | wrong number of arguments
spotizerr-redis exited with code 1
```

And of course the app fails to start because the redis service isn't running.

It's probably worth mentioning that before the latest patch I was seeing the folder permissions errors in issue #132. Those are resolved with 2.0.1 but I was seeing this configuration file error from the redis service in 2.0.0 as well.

**To Reproduce**
Attempt to deploy the container using docker-compose

**Expected behavior**
Both services in the container will start an drun without errors.

**Screenshots**

**Desktop (please complete the following information):**
 - N/A I think

**docker-compose.yaml**
```
name: spotizerr
services:
  spotizerr:
    volumes:
      - /docker/spotizerr/data:/app/data
      - /nas/Music/spotizerr/downloads:/app/downloads # <-- Change this for your music library dir
      - /docker/spotizerr/logs:/app/logs # <-- Volume for persistent logs
    ports:
      - 7171:7171
    image: cooldockerizer93/spotizerr
    container_name: spotizerr-app
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${PUID} # Replace with your desired user ID  | Remove both if you want to run as root (not recommended, might result in unreadable files)
      - PGID=${PGID} # Replace with your desired group ID | The user must have write permissions in the volume mapped to /app/downloads
      #- UMASK=${UMASK} # Optional: Sets the default file permissions for newly created files within the container.
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD} # Optional, Redis AUTH password. Leave empty if not using authentication
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - REDIS_BACKEND=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - EXPLICIT_FILTER=${EXPLICIT_FILTER} # Set to true to filter out explicit content
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
volumes:
  redis-data:
    driver: local
networks: {}

```

**.env**
```
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=
EXPLICIT_FILTER=false
PUID=1000
PGID=1000
UMASK=0022
```

**Config**
N/A 

**Logs**
```
spotizerr-redis  | Starting Redis Server
spotizerr-redis  | 
spotizerr-redis  | *** FATAL CONFIG FILE ERROR (Redis 8.0.2) ***
spotizerr-redis  | Reading the configuration file, at line 2
spotizerr-redis  | >>> 'requirepass "--appendonly" "yes"'
spotizerr-redis  | wrong number of arguments
spotizerr-redis exited with code 1
spotizerr-app exited with code 0
spotizerr-app    | Using existing group: appgroup (GID: 1000)
spotizerr-app    | Using existing user: appuser (UID: 1000)
spotizerr-app    | Setting permissions for /app directories...
spotizerr-app    | Starting application as appuser...
spotizerr-app    | 2025-05-30 20:15:23,370 - routes.utils.celery_config - INFO - Redis configuration: REDIS_URL=redis://:@redis:6379/0, REDIS_BACKEND=redis://:@redis:6379/0
spotizerr-app    | 2025-05-30 20:15:23,373 - routes.utils.watch.db - INFO - Playlists database initialized successfully at data/watch/playlists.db
spotizerr-app    | 2025-05-30 20:15:23,373 - routes.utils.watch.db - INFO - Artists database initialized successfully at data/watch/artists.db
spotizerr-app    | 2025-05-30 20:15:23,373 - routes.utils.watch.manager - INFO - Watch Scheduler: Thread started.
spotizerr-app    | 2025-05-30 20:15:23,373 - routes.utils.watch.manager - INFO - Watch Manager: Background scheduler started (includes playlists and artists).
spotizerr-app    | 2025-05-30 20:15:23,373 - routes - INFO - Playlist Watch Manager initialized and registered for shutdown.
spotizerr-app    | 2025-05-30 20:15:23,376 - routes.utils.watch.manager - INFO - Watch Scheduler: Watch feature is disabled in config. Skipping checks.
spotizerr-app    | 2025-05-30 20:15:23 [MainProcess:MainThread] [root] [INFO] - Logging system initialized
spotizerr-app    | 2025-05-30 20:15:23 [MainProcess:MainThread] [root] [INFO] - === Spotizerr Application Starting ===
spotizerr-app    | 2025-05-30 20:15:23 [MainProcess:MainThread] [root] [INFO] - Checking Redis connection to redis:6379
spotizerr-app    | 2025-05-30 20:15:23 [MainProcess:MainThread] [root] [WARNING] - Redis connection attempt 1 failed: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:23 [MainProcess:MainThread] [root] [INFO] - Retrying in 1 seconds...
spotizerr-app    | 2025-05-30 20:15:24 [MainProcess:MainThread] [root] [WARNING] - Redis connection attempt 2 failed: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:24 [MainProcess:MainThread] [root] [INFO] - Retrying in 2 seconds...
spotizerr-app    | 2025-05-30 20:15:26 [MainProcess:MainThread] [root] [WARNING] - Redis connection attempt 3 failed: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:26 [MainProcess:MainThread] [root] [INFO] - Retrying in 4 seconds...
spotizerr-app    | 2025-05-30 20:15:30 [MainProcess:MainThread] [root] [WARNING] - Redis connection attempt 4 failed: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:30 [MainProcess:MainThread] [root] [INFO] - Retrying in 8 seconds...
spotizerr-app    | 2025-05-30 20:15:38 [MainProcess:MainThread] [root] [ERROR] - Failed to connect to Redis after 5 attempts: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:38 [MainProcess:MainThread] [root] [ERROR] - Make sure Redis is running at redis:6379
spotizerr-app    | 2025-05-30 20:15:38 [MainProcess:MainThread] [root] [ERROR] - Cannot start application: Redis connection failed
spotizerr-app    | Celery Download Queue Manager initialized with max_concurrent=3
spotizerr-app    | 2025-05-30 20:15:38 [MainProcess:MainThread] [routes.utils.watch.manager] [INFO] - Watch Manager: Stopping background scheduler...
spotizerr-app    | 2025-05-30 20:15:38 [MainProcess:Thread-1 (playlist_watch_scheduler)] [routes.utils.watch.manager] [INFO] - Watch Scheduler: Thread stopped.
spotizerr-app    | 2025-05-30 20:15:38 [MainProcess:MainThread] [routes.utils.watch.manager] [INFO] - Watch Manager: Background scheduler stopped.
spotizerr-app exited with code 0
spotizerr-app    | Using existing group: appgroup (GID: 1000)
spotizerr-app    | Using existing user: appuser (UID: 1000)
spotizerr-app    | Setting permissions for /app directories...
spotizerr-app    | Starting application as appuser...
spotizerr-app    | 2025-05-30 20:15:39,317 - routes.utils.celery_config - INFO - Redis configuration: REDIS_URL=redis://:@redis:6379/0, REDIS_BACKEND=redis://:@redis:6379/0
spotizerr-app    | 2025-05-30 20:15:39,320 - routes.utils.watch.db - INFO - Playlists database initialized successfully at data/watch/playlists.db
spotizerr-app    | 2025-05-30 20:15:39,320 - routes.utils.watch.db - INFO - Artists database initialized successfully at data/watch/artists.db
spotizerr-app    | 2025-05-30 20:15:39,321 - routes.utils.watch.manager - INFO - Watch Scheduler: Thread started.
spotizerr-app    | 2025-05-30 20:15:39,321 - routes.utils.watch.manager - INFO - Watch Manager: Background scheduler started (includes playlists and artists).
spotizerr-app    | 2025-05-30 20:15:39,321 - routes - INFO - Playlist Watch Manager initialized and registered for shutdown.
spotizerr-app    | 2025-05-30 20:15:39,325 - routes.utils.watch.manager - INFO - Watch Scheduler: Watch feature is disabled in config. Skipping checks.
spotizerr-app    | 2025-05-30 20:15:39 [MainProcess:MainThread] [root] [INFO] - Logging system initialized
spotizerr-app    | 2025-05-30 20:15:39 [MainProcess:MainThread] [root] [INFO] - === Spotizerr Application Starting ===
spotizerr-app    | 2025-05-30 20:15:39 [MainProcess:MainThread] [root] [INFO] - Checking Redis connection to redis:6379
spotizerr-app    | 2025-05-30 20:15:39 [MainProcess:MainThread] [root] [WARNING] - Redis connection attempt 1 failed: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:39 [MainProcess:MainThread] [root] [INFO] - Retrying in 1 seconds...
spotizerr-app    | 2025-05-30 20:15:40 [MainProcess:MainThread] [root] [WARNING] - Redis connection attempt 2 failed: [Errno -2] Name or service not known
spotizerr-app    | 2025-05-30 20:15:40 [MainProcess:MainThread] [root] [INFO] - Retrying in 2 seconds...
spotizerr-app    | 2025-05-30 20:15:42 [MainProcess:MainThread] [root] [
```

**Version**
2.0.1
